// export const learningJourneyData = [
//   {
//     id: "modern-classrooms",
//     eyebrow: "Modern Classrooms",
//     title: "Technology that supports learning, not distracts from it.",
//     description:
//       "Every classroom is designed for clarity, curiosity, and understanding.",
//     metric: "25%",
//     metricLabel: "stronger classroom participation",
//     metricResearch: "**From internal learning observations",
//     video: "/home/features/video/classroom.mp4",
//     accentClass: "bg-sky-100 text-sky-700",
//     icon: "screen",
//   },
//   {
//     id: "communication-skills",
//     eyebrow: "Communication Skills",
//     title: "Confidence to speak, listen, present, and lead.",
//     description:
//       "Structured activities help students to express ideas with clarity and empathy.",
//     metric: "2x",
//     metricLabel: "more speaking opportunities",
//     video: "/home/features/video/communication.mp4",
//     accentClass: "bg-emerald-100 text-emerald-700",
//     icon: "message",
//   },
//   {
//     id: "innovation-labs",
//     eyebrow: "Innovation Labs",
//     title: "Hands-on spaces where ideas become working experiments.",
//     description:
//       "Students explore science, robotics, making, and design through purposeful practice.",
//     metric: "3x",
//     metricLabel: "more project-based exploration",
//     video: "/home/features/video/educraft.mp4",
//     accentClass: "bg-violet-100 text-violet-700",
//     icon: "spark",
//   },
//   {
//     id: "sports-and-wellness",
//     eyebrow: "Sports And Wellness",
//     title: "Movement, play, and wellbeing every day.",
//     description:
//       "Balanced environments support physical health, teamwork, and emotional wellbeing.",
//     metric: "50%",
//     metricLabel: "more active participation",
//     img: "/home/features/sports-wellness.webp",
//     video: "/home/features/video/sports-vid.mp4",
//     accentClass: "bg-orange-100 text-orange-700",
//     icon: "activity",
//   },
//   {
//     id: "values-and-character",
//     eyebrow: "Values And Character",
//     title: "Strong foundations for character, kindness, and responsibility.",
//     description:
//       "Daily school life reinforces respect, discipline, service, and thoughtful choices.",
//     metric: "100%",
//     metricLabel: "focus on values-led growth",
//     video: "/home/features/video/quran.mp4",
//     accentClass: "bg-rose-100 text-rose-700",
//     icon: "heart",
//   },
// ]


export const learningJourneyData = [
  {
    id: "smart-learning-spaces",
    eyebrow: "Smart Learning Spaces",
    title: "Technology that makes lessons easier to understand.",
    description:
      "Smart displays, visual lessons, and guided device use help children see concepts clearly, respond actively, and learn with confidence.",
    metric: "25%",
    metricLabel: "stronger classroom participation",
    img: "/home/features/classroom.webp",
    video: "/home/features/video/classroom.mp4",
    accentClass: "bg-blue-100 text-blue-700",
    icon: "monitor",
  },
  {
    id: "sensory-skill-development",
    eyebrow: "Sensory & Skill Development",
    title: "Learning begins with touch, movement, and discovery.",
    description:
      "Sand, water, textures, and guided activities support balance, coordination, focus, and early motor skill development.",
    metric: "40%",
    metricLabel: "more hands-on exploration",
    img: "/home/features/child-sensory.webp",
    accentClass: "bg-cyan-100 text-cyan-700",
    icon: "sparkles",
  },
  {
    id: "educraft-lab",
    eyebrow: "EduCraft Lab",
    title: "Where ideas turn into real working projects.",
    description:
      "Makerspace, robotics, coding, STEM, VR, and project-based learning help children build, test, improve, and think independently.",
    metric: "3x",
    metricLabel: "more project-based learning exposure",
    img: "/home/features/edu.webp",
    video: "/home/features/video/educraft.mp4",
    accentClass: "bg-purple-100 text-purple-700",
    icon: "bot",
  },
  {
    id: "design-technology-exploration",
    eyebrow: "Design & Technology",
    title: "Children learn how things work by exploring them safely.",
    description:
      "Practical activities introduce reverse engineering, light carpentry, electrical basics, plumbing fundamentals, and everyday problem-solving.",
    metric: "5+",
    metricLabel: "practical skill areas introduced",
    img: "/home/features/reverse-eng.webp",
    accentClass: "bg-amber-100 text-amber-700",
    icon: "wrench",
  },
  {
    id: "art-creative-studios",
    eyebrow: "Art & Creative Studios",
    title: "A calm space for imagination, expression, and fine skills.",
    description:
      "Drawing, painting, craft, textile work, and creative activities help children express ideas while strengthening focus and hand control.",
    metric: "30%",
    metricLabel: "more creative expression time",
    img: "/home/features/creative-1.webp",
    accentClass: "bg-pink-100 text-pink-700",
    icon: "palette",
  },
  {
    id: "food-science-life-skills",
    eyebrow: "Food Science & Life Skills",
    title: "Healthy habits shaped through real experience.",
    description:
      "Children explore cooking basics, nutrition, food science, cleanliness, responsibility, and healthy habits through guided practical learning.",
    metric: "4",
    metricLabel: "life-skill learning pillars",
    img: "/home/features/food.webp",
    accentClass: "bg-lime-100 text-lime-700",
    icon: "chef-hat",
  },
  {
    id: "auditorium-indoor-sports",
    eyebrow: "Auditorium & Indoor Hall",
    title: "Confidence grows when children get a stage.",
    description:
      "A dedicated indoor hall supports storytelling, public speaking, performances, assemblies, movement activities, and group confidence building.",
    metric: "2x",
    metricLabel: "more opportunities to perform and present",
    img: "/home/features/speaking.webp",
    video: "/home/features/video/communication.mp4",
    accentClass: "bg-red-100 text-red-700",
    icon: "mic",
  },
  {
    id: "sports-and-wellness",
    eyebrow: "Sports & Wellness",
    title: "Movement, play and wellbeing every day.",
    description:
      "Indoor activity rooms, outdoor play zones, sports grounds, running tracks, and wellbeing spaces support fitness, teamwork, and emotional balance.",
    metric: "50%",
    metricLabel: "more active participation",
    img: "/home/features/sports-wellness.webp",
    accentClass: "bg-orange-100 text-orange-700",
    icon: "activity",
  },
  {
    id: "kids-pool-swimming",
    eyebrow: "Kids’ Pool & Swimming",
    title: "Water confidence built safely from an early age.",
    description:
      "Child-friendly pools and supervised swimming programs help children develop confidence, coordination, discipline, and water safety awareness.",
    metric: "100%",
    metricLabel: "supervised water learning",
    img: "/home/features/swim.webp",
    accentClass: "bg-sky-100 text-sky-700",
    icon: "waves",
  },
  {
    id: "islamic-garden-nature-learning",
    eyebrow: "Islamic Garden & Nature",
    title: "A peaceful place to learn from nature and reflection.",
    description:
      "Qur’anic plants, outdoor learning, sustainability activities, and reflection spaces help children connect knowledge with gratitude and care.",
    metric: "20+",
    metricLabel: "nature and reflection experiences",
    img: "/home/features/garden2.webp",
    accentClass: "bg-emerald-100 text-emerald-700",
    icon: "leaf",
  },
  {
    id: "prayer-room-mosque",
    eyebrow: "Prayer Room / Mosque",
    title: "A serene space for values, prayer, and inner calm.",
    description:
      "A dedicated spiritual environment supports prayer, reflection, discipline, gratitude, and value-based character development.",
    metric: "5x",
    metricLabel: "daily moments for reflection and prayer",
    img: "/home/features/masjid.webp",
    video: "/home/features/video/quran.mp4",
    accentClass: "bg-teal-100 text-teal-700",
    icon: "moon",
  },
  {
    id: "smart-transport-connectivity",
    eyebrow: "Smart Transport & Safety",
    title: "Safe journeys with parents always connected.",
    description:
      "GPS-tracked transport, secure digital systems, and parent communication tools help families stay informed from pickup to drop-off.",
    metric: "100%",
    metricLabel: "GPS-enabled school transport",
    img: "/home/features/smart-tracking.webp",
    accentClass: "bg-indigo-100 text-indigo-700",
    icon: "bus",
  },
]
